/*
 * Copyright (c) 2013-2015, ARM Limited and Contributors. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of ARM nor the names of its contributors may be used
 * to endorse or promote products derived from this software without specific
 * prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __APU_H__
#define __APU_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * APU Base Address
 */
#define APU_BASEADDR      0xFD5C0000

/**
 * Register: APU_ERR_CTRL
 */
#define APU_ERR_CTRL    ( ( APU_BASEADDR ) + 0x00000000 )
#define APU_ERR_CTRL_DEFVAL   0x0

#define APU_ERR_CTRL_PSLVERR_SHIFT   0
#define APU_ERR_CTRL_PSLVERR_WIDTH   1
#define APU_ERR_CTRL_PSLVERR_MASK    0x00000001
#define APU_ERR_CTRL_PSLVERR_DEFVAL  0x0

/**
 * Register: APU_ISR
 */
#define APU_ISR    ( ( APU_BASEADDR ) + 0x00000010 )
#define APU_ISR_DEFVAL   0x0

#define APU_ISR_INV_APB_SHIFT   0
#define APU_ISR_INV_APB_WIDTH   1
#define APU_ISR_INV_APB_MASK    0x00000001
#define APU_ISR_INV_APB_DEFVAL  0x0

/**
 * Register: APU_IMR
 */
#define APU_IMR    ( ( APU_BASEADDR ) + 0x00000014 )
#define APU_IMR_DEFVAL   0x1

#define APU_IMR_INV_APB_SHIFT   0
#define APU_IMR_INV_APB_WIDTH   1
#define APU_IMR_INV_APB_MASK    0x00000001
#define APU_IMR_INV_APB_DEFVAL  0x1

/**
 * Register: APU_IEN
 */
#define APU_IEN    ( ( APU_BASEADDR ) + 0x00000018 )
#define APU_IEN_DEFVAL   0x1

#define APU_IEN_INV_APB_SHIFT   0
#define APU_IEN_INV_APB_WIDTH   1
#define APU_IEN_INV_APB_MASK    0x00000001
#define APU_IEN_INV_APB_DEFVAL  0x1

/**
 * Register: APU_IDS
 */
#define APU_IDS    ( ( APU_BASEADDR ) + 0x0000001C )
#define APU_IDS_DEFVAL   0x1

#define APU_IDS_INV_APB_SHIFT   0
#define APU_IDS_INV_APB_WIDTH   1
#define APU_IDS_INV_APB_MASK    0x00000001
#define APU_IDS_INV_APB_DEFVAL  0x1

/**
 * Register: APU_CONFIG_0
 */
#define APU_CONFIG_0    ( ( APU_BASEADDR ) + 0x00000020 )
#define APU_CONFIG_0_DEFVAL   0xf0f

#define APU_CONFIG_0_CFGTE_SHIFT   24
#define APU_CONFIG_0_CFGTE_WIDTH   4
#define APU_CONFIG_0_CFGTE_MASK    0x0f000000
#define APU_CONFIG_0_CFGTE_DEFVAL  0x0

#define APU_CONFIG_0_CFGEND_SHIFT   16
#define APU_CONFIG_0_CFGEND_WIDTH   4
#define APU_CONFIG_0_CFGEND_MASK    0x000f0000
#define APU_CONFIG_0_CFGEND_DEFVAL  0x0

#define APU_CONFIG_0_VINITHI_SHIFT   8
#define APU_CONFIG_0_VINITHI_WIDTH   4
#define APU_CONFIG_0_VINITHI_MASK    0x00000f00
#define APU_CONFIG_0_VINITHI_DEFVAL  0xf

#define APU_CONFIG_0_AA64NAA32_SHIFT   0
#define APU_CONFIG_0_AA64NAA32_WIDTH   4
#define APU_CONFIG_0_AA64NAA32_MASK    0x0000000f
#define APU_CONFIG_0_AA64NAA32_DEFVAL  0xf

/**
 * Register: APU_CONFIG_1
 */
#define APU_CONFIG_1    ( ( APU_BASEADDR ) + 0x00000024 )
#define APU_CONFIG_1_DEFVAL   0x0

#define APU_CONFIG_1_L2RSTDISABLE_SHIFT   29
#define APU_CONFIG_1_L2RSTDISABLE_WIDTH   1
#define APU_CONFIG_1_L2RSTDISABLE_MASK    0x20000000
#define APU_CONFIG_1_L2RSTDISABLE_DEFVAL  0x0

#define APU_CONFIG_1_L1RSTDISABLE_SHIFT   28
#define APU_CONFIG_1_L1RSTDISABLE_WIDTH   1
#define APU_CONFIG_1_L1RSTDISABLE_MASK    0x10000000
#define APU_CONFIG_1_L1RSTDISABLE_DEFVAL  0x0

#define APU_CONFIG_1_CP15DISABLE_SHIFT   0
#define APU_CONFIG_1_CP15DISABLE_WIDTH   4
#define APU_CONFIG_1_CP15DISABLE_MASK    0x0000000f
#define APU_CONFIG_1_CP15DISABLE_DEFVAL  0x0

/**
 * Register: APU_CONFIG_2
 */
#define APU_CONFIG_2    ( ( APU_BASEADDR ) + 0x00000028 )
#define APU_CONFIG_2_DEFVAL   0x0

#define APU_CONFIG_2_BRDC_OUTER_SHIFT   3
#define APU_CONFIG_2_BRDC_OUTER_WIDTH   1
#define APU_CONFIG_2_BRDC_OUTER_MASK    0x00000008
#define APU_CONFIG_2_BRDC_OUTER_DEFVAL  0x0

#define APU_CONFIG_2_BRDC_INNER_SHIFT   2
#define APU_CONFIG_2_BRDC_INNER_WIDTH   1
#define APU_CONFIG_2_BRDC_INNER_MASK    0x00000004
#define APU_CONFIG_2_BRDC_INNER_DEFVAL  0x0

#define APU_CONFIG_2_BRDC_CMNT_SHIFT   1
#define APU_CONFIG_2_BRDC_CMNT_WIDTH   1
#define APU_CONFIG_2_BRDC_CMNT_MASK    0x00000002
#define APU_CONFIG_2_BRDC_CMNT_DEFVAL  0x0

#define APU_CONFIG_2_BRDC_BARRIER_SHIFT   0
#define APU_CONFIG_2_BRDC_BARRIER_WIDTH   1
#define APU_CONFIG_2_BRDC_BARRIER_MASK    0x00000001
#define APU_CONFIG_2_BRDC_BARRIER_DEFVAL  0x0

/**
 * Register: APU_RVBARADDR0L
 */
#define APU_RVBARADDR0L    ( ( APU_BASEADDR ) + 0x00000040 )
#define APU_RVBARADDR0L_DEFVAL   0xffff0000

#define APU_RVBARADDR0L_ADDR_SHIFT   2
#define APU_RVBARADDR0L_ADDR_WIDTH   30
#define APU_RVBARADDR0L_ADDR_MASK    0xfffffffc
#define APU_RVBARADDR0L_ADDR_DEFVAL  0x3fffc000

/**
 * Register: APU_RVBARADDR0H
 */
#define APU_RVBARADDR0H    ( ( APU_BASEADDR ) + 0x00000044 )
#define APU_RVBARADDR0H_DEFVAL   0x0

#define APU_RVBARADDR0H_ADDR_SHIFT   0
#define APU_RVBARADDR0H_ADDR_WIDTH   8
#define APU_RVBARADDR0H_ADDR_MASK    0x000000ff
#define APU_RVBARADDR0H_ADDR_DEFVAL  0x0

/**
 * Register: APU_RVBARADDR1L
 */
#define APU_RVBARADDR1L    ( ( APU_BASEADDR ) + 0x00000048 )
#define APU_RVBARADDR1L_DEFVAL   0xffff0000

#define APU_RVBARADDR1L_ADDR_SHIFT   2
#define APU_RVBARADDR1L_ADDR_WIDTH   30
#define APU_RVBARADDR1L_ADDR_MASK    0xfffffffc
#define APU_RVBARADDR1L_ADDR_DEFVAL  0x3fffc000

/**
 * Register: APU_RVBARADDR1H
 */
#define APU_RVBARADDR1H    ( ( APU_BASEADDR ) + 0x0000004C )
#define APU_RVBARADDR1H_DEFVAL   0x0

#define APU_RVBARADDR1H_ADDR_SHIFT   0
#define APU_RVBARADDR1H_ADDR_WIDTH   8
#define APU_RVBARADDR1H_ADDR_MASK    0x000000ff
#define APU_RVBARADDR1H_ADDR_DEFVAL  0x0

/**
 * Register: APU_RVBARADDR2L
 */
#define APU_RVBARADDR2L    ( ( APU_BASEADDR ) + 0x00000050 )
#define APU_RVBARADDR2L_DEFVAL   0xffff0000

#define APU_RVBARADDR2L_ADDR_SHIFT   2
#define APU_RVBARADDR2L_ADDR_WIDTH   30
#define APU_RVBARADDR2L_ADDR_MASK    0xfffffffc
#define APU_RVBARADDR2L_ADDR_DEFVAL  0x3fffc000

/**
 * Register: APU_RVBARADDR2H
 */
#define APU_RVBARADDR2H    ( ( APU_BASEADDR ) + 0x00000054 )
#define APU_RVBARADDR2H_DEFVAL   0x0

#define APU_RVBARADDR2H_ADDR_SHIFT   0
#define APU_RVBARADDR2H_ADDR_WIDTH   8
#define APU_RVBARADDR2H_ADDR_MASK    0x000000ff
#define APU_RVBARADDR2H_ADDR_DEFVAL  0x0

/**
 * Register: APU_RVBARADDR3L
 */
#define APU_RVBARADDR3L    ( ( APU_BASEADDR ) + 0x00000058 )
#define APU_RVBARADDR3L_DEFVAL   0xffff0000

#define APU_RVBARADDR3L_ADDR_SHIFT   2
#define APU_RVBARADDR3L_ADDR_WIDTH   30
#define APU_RVBARADDR3L_ADDR_MASK    0xfffffffc
#define APU_RVBARADDR3L_ADDR_DEFVAL  0x3fffc000

/**
 * Register: APU_RVBARADDR3H
 */
#define APU_RVBARADDR3H    ( ( APU_BASEADDR ) + 0x0000005C )
#define APU_RVBARADDR3H_DEFVAL   0x0

#define APU_RVBARADDR3H_ADDR_SHIFT   0
#define APU_RVBARADDR3H_ADDR_WIDTH   8
#define APU_RVBARADDR3H_ADDR_MASK    0x000000ff
#define APU_RVBARADDR3H_ADDR_DEFVAL  0x0

/**
 * Register: APU_SNOOP_CTRL
 */
#define APU_SNOOP_CTRL    ( ( APU_BASEADDR ) + 0x00000080 )
#define APU_SNOOP_CTRL_DEFVAL   0x0

#define APU_SNOOP_CTRL_ACE_INACT_SHIFT   4
#define APU_SNOOP_CTRL_ACE_INACT_WIDTH   1
#define APU_SNOOP_CTRL_ACE_INACT_MASK    0x00000010
#define APU_SNOOP_CTRL_ACE_INACT_DEFVAL  0x0

#define APU_SNOOP_CTRL_ACP_INACT_SHIFT   0
#define APU_SNOOP_CTRL_ACP_INACT_WIDTH   1
#define APU_SNOOP_CTRL_ACP_INACT_MASK    0x00000001
#define APU_SNOOP_CTRL_ACP_INACT_DEFVAL  0x0

/**
 * Register: APU_PWRCTL
 */
#define APU_PWRCTL    ( ( APU_BASEADDR ) + 0x00000090 )
#define APU_PWRCTL_DEFVAL   0x0

#define APU_PWRCTL_CLREXMONREQ_SHIFT   17
#define APU_PWRCTL_CLREXMONREQ_WIDTH   1
#define APU_PWRCTL_CLREXMONREQ_MASK    0x00020000
#define APU_PWRCTL_CLREXMONREQ_DEFVAL  0x0

#define APU_PWRCTL_L2FLUSHREQ_SHIFT   16
#define APU_PWRCTL_L2FLUSHREQ_WIDTH   1
#define APU_PWRCTL_L2FLUSHREQ_MASK    0x00010000
#define APU_PWRCTL_L2FLUSHREQ_DEFVAL  0x0

#define APU_PWRCTL_CPUPWRDWNREQ_SHIFT   0
#define APU_PWRCTL_CPUPWRDWNREQ_WIDTH   4
#define APU_PWRCTL_CPUPWRDWNREQ_MASK    0x0000000f
#define APU_PWRCTL_CPUPWRDWNREQ_DEFVAL  0x0

/**
 * Register: APU_PWRSTAT
 */
#define APU_PWRSTAT    ( ( APU_BASEADDR ) + 0x00000094 )
#define APU_PWRSTAT_DEFVAL   0x0

#define APU_PWRSTAT_CLREXMONACK_SHIFT   17
#define APU_PWRSTAT_CLREXMONACK_WIDTH   1
#define APU_PWRSTAT_CLREXMONACK_MASK    0x00020000
#define APU_PWRSTAT_CLREXMONACK_DEFVAL  0x0

#define APU_PWRSTAT_L2FLUSHDONE_SHIFT   16
#define APU_PWRSTAT_L2FLUSHDONE_WIDTH   1
#define APU_PWRSTAT_L2FLUSHDONE_MASK    0x00010000
#define APU_PWRSTAT_L2FLUSHDONE_DEFVAL  0x0

#define APU_PWRSTAT_DBGNOPWRDWN_SHIFT   0
#define APU_PWRSTAT_DBGNOPWRDWN_WIDTH   4
#define APU_PWRSTAT_DBGNOPWRDWN_MASK    0x0000000f
#define APU_PWRSTAT_DBGNOPWRDWN_DEFVAL  0x0

/**
 * Register: APU_ECO
 */
#define APU_ECO    ( ( APU_BASEADDR ) + 0x000000EC )
#define APU_ECO_DEFVAL   0x0

#define APU_ECO_SPARE_SHIFT   0
#define APU_ECO_SPARE_WIDTH   32
#define APU_ECO_SPARE_MASK    0xffffffff
#define APU_ECO_SPARE_DEFVAL  0x0

/**
 * Register: APU_RAM_ADJ_0
 */
#define APU_RAM_ADJ_0    ( ( APU_BASEADDR ) + 0x000000F0 )
#define APU_RAM_ADJ_0_DEFVAL   0xa0a0a0a

#define APU_RAM_ADJ_0_L1_ITAG_EMAS_SHIFT   29
#define APU_RAM_ADJ_0_L1_ITAG_EMAS_WIDTH   1
#define APU_RAM_ADJ_0_L1_ITAG_EMAS_MASK    0x20000000
#define APU_RAM_ADJ_0_L1_ITAG_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_0_L1_ITAG_EMAW_SHIFT   27
#define APU_RAM_ADJ_0_L1_ITAG_EMAW_WIDTH   2
#define APU_RAM_ADJ_0_L1_ITAG_EMAW_MASK    0x18000000
#define APU_RAM_ADJ_0_L1_ITAG_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_0_L1_ITAG_EMA_SHIFT   24
#define APU_RAM_ADJ_0_L1_ITAG_EMA_WIDTH   3
#define APU_RAM_ADJ_0_L1_ITAG_EMA_MASK    0x07000000
#define APU_RAM_ADJ_0_L1_ITAG_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_0_L1_IDATA_EMAS_SHIFT   21
#define APU_RAM_ADJ_0_L1_IDATA_EMAS_WIDTH   1
#define APU_RAM_ADJ_0_L1_IDATA_EMAS_MASK    0x00200000
#define APU_RAM_ADJ_0_L1_IDATA_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_0_L1_IDATA_EMAW_SHIFT   19
#define APU_RAM_ADJ_0_L1_IDATA_EMAW_WIDTH   2
#define APU_RAM_ADJ_0_L1_IDATA_EMAW_MASK    0x00180000
#define APU_RAM_ADJ_0_L1_IDATA_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_0_L1_IDATA_EMA_SHIFT   16
#define APU_RAM_ADJ_0_L1_IDATA_EMA_WIDTH   3
#define APU_RAM_ADJ_0_L1_IDATA_EMA_MASK    0x00070000
#define APU_RAM_ADJ_0_L1_IDATA_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_0_L1_DTAG_EMAS_SHIFT   13
#define APU_RAM_ADJ_0_L1_DTAG_EMAS_WIDTH   1
#define APU_RAM_ADJ_0_L1_DTAG_EMAS_MASK    0x00002000
#define APU_RAM_ADJ_0_L1_DTAG_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_0_L1_DTAG_EMAW_SHIFT   11
#define APU_RAM_ADJ_0_L1_DTAG_EMAW_WIDTH   2
#define APU_RAM_ADJ_0_L1_DTAG_EMAW_MASK    0x00001800
#define APU_RAM_ADJ_0_L1_DTAG_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_0_L1_DTAG_EMA_SHIFT   8
#define APU_RAM_ADJ_0_L1_DTAG_EMA_WIDTH   3
#define APU_RAM_ADJ_0_L1_DTAG_EMA_MASK    0x00000700
#define APU_RAM_ADJ_0_L1_DTAG_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_0_L1_DDATA_EMAS_SHIFT   5
#define APU_RAM_ADJ_0_L1_DDATA_EMAS_WIDTH   1
#define APU_RAM_ADJ_0_L1_DDATA_EMAS_MASK    0x00000020
#define APU_RAM_ADJ_0_L1_DDATA_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_0_L1_DDATA_EMAW_SHIFT   3
#define APU_RAM_ADJ_0_L1_DDATA_EMAW_WIDTH   2
#define APU_RAM_ADJ_0_L1_DDATA_EMAW_MASK    0x00000018
#define APU_RAM_ADJ_0_L1_DDATA_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_0_L1_DDATA_EMA_SHIFT   0
#define APU_RAM_ADJ_0_L1_DDATA_EMA_WIDTH   3
#define APU_RAM_ADJ_0_L1_DDATA_EMA_MASK    0x00000007
#define APU_RAM_ADJ_0_L1_DDATA_EMA_DEFVAL  0x2

/**
 * Register: APU_RAM_ADJ_1
 */
#define APU_RAM_ADJ_1    ( ( APU_BASEADDR ) + 0x000000F4 )
#define APU_RAM_ADJ_1_DEFVAL   0xa0a0a0a

#define APU_RAM_ADJ_1_TLB_EMAS_SHIFT   29
#define APU_RAM_ADJ_1_TLB_EMAS_WIDTH   1
#define APU_RAM_ADJ_1_TLB_EMAS_MASK    0x20000000
#define APU_RAM_ADJ_1_TLB_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_1_TLB_EMAW_SHIFT   27
#define APU_RAM_ADJ_1_TLB_EMAW_WIDTH   2
#define APU_RAM_ADJ_1_TLB_EMAW_MASK    0x18000000
#define APU_RAM_ADJ_1_TLB_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_1_TLB_EMA_SHIFT   24
#define APU_RAM_ADJ_1_TLB_EMA_WIDTH   3
#define APU_RAM_ADJ_1_TLB_EMA_MASK    0x07000000
#define APU_RAM_ADJ_1_TLB_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_1_DIRTY_EMAS_SHIFT   21
#define APU_RAM_ADJ_1_DIRTY_EMAS_WIDTH   1
#define APU_RAM_ADJ_1_DIRTY_EMAS_MASK    0x00200000
#define APU_RAM_ADJ_1_DIRTY_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_1_DIRTY_EMAW_SHIFT   19
#define APU_RAM_ADJ_1_DIRTY_EMAW_WIDTH   2
#define APU_RAM_ADJ_1_DIRTY_EMAW_MASK    0x00180000
#define APU_RAM_ADJ_1_DIRTY_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_1_DIRTY_EMA_SHIFT   16
#define APU_RAM_ADJ_1_DIRTY_EMA_WIDTH   3
#define APU_RAM_ADJ_1_DIRTY_EMA_MASK    0x00070000
#define APU_RAM_ADJ_1_DIRTY_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_1_BTAC1_EMAS_SHIFT   13
#define APU_RAM_ADJ_1_BTAC1_EMAS_WIDTH   1
#define APU_RAM_ADJ_1_BTAC1_EMAS_MASK    0x00002000
#define APU_RAM_ADJ_1_BTAC1_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_1_BTAC1_EMAW_SHIFT   11
#define APU_RAM_ADJ_1_BTAC1_EMAW_WIDTH   2
#define APU_RAM_ADJ_1_BTAC1_EMAW_MASK    0x00001800
#define APU_RAM_ADJ_1_BTAC1_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_1_BTAC1_EMA_SHIFT   8
#define APU_RAM_ADJ_1_BTAC1_EMA_WIDTH   3
#define APU_RAM_ADJ_1_BTAC1_EMA_MASK    0x00000700
#define APU_RAM_ADJ_1_BTAC1_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_1_BTAC0_EMAS_SHIFT   5
#define APU_RAM_ADJ_1_BTAC0_EMAS_WIDTH   1
#define APU_RAM_ADJ_1_BTAC0_EMAS_MASK    0x00000020
#define APU_RAM_ADJ_1_BTAC0_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_1_BTAC0_EMAW_SHIFT   3
#define APU_RAM_ADJ_1_BTAC0_EMAW_WIDTH   2
#define APU_RAM_ADJ_1_BTAC0_EMAW_MASK    0x00000018
#define APU_RAM_ADJ_1_BTAC0_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_1_BTAC0_EMA_SHIFT   0
#define APU_RAM_ADJ_1_BTAC0_EMA_WIDTH   3
#define APU_RAM_ADJ_1_BTAC0_EMA_MASK    0x00000007
#define APU_RAM_ADJ_1_BTAC0_EMA_DEFVAL  0x2

/**
 * Register: APU_RAM_ADJ_2
 */
#define APU_RAM_ADJ_2    ( ( APU_BASEADDR ) + 0x000000F8 )
#define APU_RAM_ADJ_2_DEFVAL   0xa000a0a

#define APU_RAM_ADJ_2_ETF_EMAS_SHIFT   29
#define APU_RAM_ADJ_2_ETF_EMAS_WIDTH   1
#define APU_RAM_ADJ_2_ETF_EMAS_MASK    0x20000000
#define APU_RAM_ADJ_2_ETF_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_2_ETF_EMAW_SHIFT   27
#define APU_RAM_ADJ_2_ETF_EMAW_WIDTH   2
#define APU_RAM_ADJ_2_ETF_EMAW_MASK    0x18000000
#define APU_RAM_ADJ_2_ETF_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_2_ETF_EMA_SHIFT   24
#define APU_RAM_ADJ_2_ETF_EMA_WIDTH   3
#define APU_RAM_ADJ_2_ETF_EMA_MASK    0x07000000
#define APU_RAM_ADJ_2_ETF_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_2_SCU_TAG_EMAS_SHIFT   13
#define APU_RAM_ADJ_2_SCU_TAG_EMAS_WIDTH   1
#define APU_RAM_ADJ_2_SCU_TAG_EMAS_MASK    0x00002000
#define APU_RAM_ADJ_2_SCU_TAG_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_2_SCU_TAG_EMAW_SHIFT   11
#define APU_RAM_ADJ_2_SCU_TAG_EMAW_WIDTH   2
#define APU_RAM_ADJ_2_SCU_TAG_EMAW_MASK    0x00001800
#define APU_RAM_ADJ_2_SCU_TAG_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_2_SCU_TAG_EMA_SHIFT   8
#define APU_RAM_ADJ_2_SCU_TAG_EMA_WIDTH   3
#define APU_RAM_ADJ_2_SCU_TAG_EMA_MASK    0x00000700
#define APU_RAM_ADJ_2_SCU_TAG_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_2_L2_VICTIM_EMAS_SHIFT   5
#define APU_RAM_ADJ_2_L2_VICTIM_EMAS_WIDTH   1
#define APU_RAM_ADJ_2_L2_VICTIM_EMAS_MASK    0x00000020
#define APU_RAM_ADJ_2_L2_VICTIM_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_2_L2_VICTIM_EMAW_SHIFT   3
#define APU_RAM_ADJ_2_L2_VICTIM_EMAW_WIDTH   2
#define APU_RAM_ADJ_2_L2_VICTIM_EMAW_MASK    0x00000018
#define APU_RAM_ADJ_2_L2_VICTIM_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_2_L2_VICTIM_EMA_SHIFT   0
#define APU_RAM_ADJ_2_L2_VICTIM_EMA_WIDTH   3
#define APU_RAM_ADJ_2_L2_VICTIM_EMA_MASK    0x00000007
#define APU_RAM_ADJ_2_L2_VICTIM_EMA_DEFVAL  0x2

/**
 * Register: APU_RAM_ADJ_3
 */
#define APU_RAM_ADJ_3    ( ( APU_BASEADDR ) + 0x000000FC )
#define APU_RAM_ADJ_3_DEFVAL   0xa0a0a0a

#define APU_RAM_ADJ_3_L2_TAGECC_EMAS_SHIFT   29
#define APU_RAM_ADJ_3_L2_TAGECC_EMAS_WIDTH   1
#define APU_RAM_ADJ_3_L2_TAGECC_EMAS_MASK    0x20000000
#define APU_RAM_ADJ_3_L2_TAGECC_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_3_L2_TAGECC_EMAW_SHIFT   27
#define APU_RAM_ADJ_3_L2_TAGECC_EMAW_WIDTH   2
#define APU_RAM_ADJ_3_L2_TAGECC_EMAW_MASK    0x18000000
#define APU_RAM_ADJ_3_L2_TAGECC_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_3_L2_TAGECC_EMA_SHIFT   24
#define APU_RAM_ADJ_3_L2_TAGECC_EMA_WIDTH   3
#define APU_RAM_ADJ_3_L2_TAGECC_EMA_MASK    0x07000000
#define APU_RAM_ADJ_3_L2_TAGECC_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_3_L2_TAG_EMAS_SHIFT   21
#define APU_RAM_ADJ_3_L2_TAG_EMAS_WIDTH   1
#define APU_RAM_ADJ_3_L2_TAG_EMAS_MASK    0x00200000
#define APU_RAM_ADJ_3_L2_TAG_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_3_L2_TAG_EMAW_SHIFT   19
#define APU_RAM_ADJ_3_L2_TAG_EMAW_WIDTH   2
#define APU_RAM_ADJ_3_L2_TAG_EMAW_MASK    0x00180000
#define APU_RAM_ADJ_3_L2_TAG_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_3_L2_TAG_EMA_SHIFT   16
#define APU_RAM_ADJ_3_L2_TAG_EMA_WIDTH   3
#define APU_RAM_ADJ_3_L2_TAG_EMA_MASK    0x00070000
#define APU_RAM_ADJ_3_L2_TAG_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_3_L2_DATAECC_EMAS_SHIFT   13
#define APU_RAM_ADJ_3_L2_DATAECC_EMAS_WIDTH   1
#define APU_RAM_ADJ_3_L2_DATAECC_EMAS_MASK    0x00002000
#define APU_RAM_ADJ_3_L2_DATAECC_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_3_L2_DATAECC_EMAW_SHIFT   11
#define APU_RAM_ADJ_3_L2_DATAECC_EMAW_WIDTH   2
#define APU_RAM_ADJ_3_L2_DATAECC_EMAW_MASK    0x00001800
#define APU_RAM_ADJ_3_L2_DATAECC_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_3_L2_DATAECC_EMA_SHIFT   8
#define APU_RAM_ADJ_3_L2_DATAECC_EMA_WIDTH   3
#define APU_RAM_ADJ_3_L2_DATAECC_EMA_MASK    0x00000700
#define APU_RAM_ADJ_3_L2_DATAECC_EMA_DEFVAL  0x2

#define APU_RAM_ADJ_3_L2_DATA_EMAS_SHIFT   5
#define APU_RAM_ADJ_3_L2_DATA_EMAS_WIDTH   1
#define APU_RAM_ADJ_3_L2_DATA_EMAS_MASK    0x00000020
#define APU_RAM_ADJ_3_L2_DATA_EMAS_DEFVAL  0x0

#define APU_RAM_ADJ_3_L2_DATA_EMAW_SHIFT   3
#define APU_RAM_ADJ_3_L2_DATA_EMAW_WIDTH   2
#define APU_RAM_ADJ_3_L2_DATA_EMAW_MASK    0x00000018
#define APU_RAM_ADJ_3_L2_DATA_EMAW_DEFVAL  0x1

#define APU_RAM_ADJ_3_L2_DATA_EMA_SHIFT   0
#define APU_RAM_ADJ_3_L2_DATA_EMA_WIDTH   3
#define APU_RAM_ADJ_3_L2_DATA_EMA_MASK    0x00000007
#define APU_RAM_ADJ_3_L2_DATA_EMA_DEFVAL  0x2

/**
 * Register: APU_XPD_REG0
 */
#define APU_XPD_REG0    ( ( APU_BASEADDR ) + 0x00000600 )
#define APU_XPD_REG0_DEFVAL   0x0

#define APU_XPD_REG0_PRE_LOAD_SHIFT   0
#define APU_XPD_REG0_PRE_LOAD_WIDTH   32
#define APU_XPD_REG0_PRE_LOAD_MASK    0xffffffff
#define APU_XPD_REG0_PRE_LOAD_DEFVAL  0x0

/**
 * Register: APU_XPD_REG1
 */
#define APU_XPD_REG1    ( ( APU_BASEADDR ) + 0x00000604 )
#define APU_XPD_REG1_DEFVAL   0x0

#define APU_XPD_REG1_EXPECTED_SHIFT   0
#define APU_XPD_REG1_EXPECTED_WIDTH   32
#define APU_XPD_REG1_EXPECTED_MASK    0xffffffff
#define APU_XPD_REG1_EXPECTED_DEFVAL  0x0

/**
 * Register: APU_XPD_CTRL0
 */
#define APU_XPD_CTRL0    ( ( APU_BASEADDR ) + 0x00000608 )
#define APU_XPD_CTRL0_DEFVAL   0x0

#define APU_XPD_CTRL0_DELAY_SPARE_SHIFT   25
#define APU_XPD_CTRL0_DELAY_SPARE_WIDTH   5
#define APU_XPD_CTRL0_DELAY_SPARE_MASK    0x3e000000
#define APU_XPD_CTRL0_DELAY_SPARE_DEFVAL  0x0

#define APU_XPD_CTRL0_CMP_SEL_SHIFT   24
#define APU_XPD_CTRL0_CMP_SEL_WIDTH   1
#define APU_XPD_CTRL0_CMP_SEL_MASK    0x01000000
#define APU_XPD_CTRL0_CMP_SEL_DEFVAL  0x0

#define APU_XPD_CTRL0_DELAY_CELL_TYPE_SHIFT   19
#define APU_XPD_CTRL0_DELAY_CELL_TYPE_WIDTH   5
#define APU_XPD_CTRL0_DELAY_CELL_TYPE_MASK    0x00f80000
#define APU_XPD_CTRL0_DELAY_CELL_TYPE_DEFVAL  0x0

#define APU_XPD_CTRL0_DELAY_VT_TYPE_SHIFT   17
#define APU_XPD_CTRL0_DELAY_VT_TYPE_WIDTH   2
#define APU_XPD_CTRL0_DELAY_VT_TYPE_MASK    0x00060000
#define APU_XPD_CTRL0_DELAY_VT_TYPE_DEFVAL  0x0

#define APU_XPD_CTRL0_DELAY_VALUE_SHIFT   6
#define APU_XPD_CTRL0_DELAY_VALUE_WIDTH   11
#define APU_XPD_CTRL0_DELAY_VALUE_MASK    0x0001ffc0
#define APU_XPD_CTRL0_DELAY_VALUE_DEFVAL  0x0

#define APU_XPD_CTRL0_PATH_SEL_SHIFT   0
#define APU_XPD_CTRL0_PATH_SEL_WIDTH   6
#define APU_XPD_CTRL0_PATH_SEL_MASK    0x0000003f
#define APU_XPD_CTRL0_PATH_SEL_DEFVAL  0x0

/**
 * Register: APU_XPD_CTRL1
 */
#define APU_XPD_CTRL1    ( ( APU_BASEADDR ) + 0x0000060C )
#define APU_XPD_CTRL1_DEFVAL   0x0

#define APU_XPD_CTRL1_CLK_SPARE_SHIFT   12
#define APU_XPD_CTRL1_CLK_SPARE_WIDTH   4
#define APU_XPD_CTRL1_CLK_SPARE_MASK    0x0000f000
#define APU_XPD_CTRL1_CLK_SPARE_DEFVAL  0x0

#define APU_XPD_CTRL1_CLK_PHASE_SEL_SHIFT   10
#define APU_XPD_CTRL1_CLK_PHASE_SEL_WIDTH   2
#define APU_XPD_CTRL1_CLK_PHASE_SEL_MASK    0x00000c00
#define APU_XPD_CTRL1_CLK_PHASE_SEL_DEFVAL  0x0

#define APU_XPD_CTRL1_CLK_VT_TYPE_SHIFT   8
#define APU_XPD_CTRL1_CLK_VT_TYPE_WIDTH   2
#define APU_XPD_CTRL1_CLK_VT_TYPE_MASK    0x00000300
#define APU_XPD_CTRL1_CLK_VT_TYPE_DEFVAL  0x0

#define APU_XPD_CTRL1_CLK_CELL_TYPE_SHIFT   6
#define APU_XPD_CTRL1_CLK_CELL_TYPE_WIDTH   2
#define APU_XPD_CTRL1_CLK_CELL_TYPE_MASK    0x000000c0
#define APU_XPD_CTRL1_CLK_CELL_TYPE_DEFVAL  0x0

#define APU_XPD_CTRL1_CLK_INSERT_DLY_SHIFT   2
#define APU_XPD_CTRL1_CLK_INSERT_DLY_WIDTH   4
#define APU_XPD_CTRL1_CLK_INSERT_DLY_MASK    0x0000003c
#define APU_XPD_CTRL1_CLK_INSERT_DLY_DEFVAL  0x0

#define APU_XPD_CTRL1_CLK_SEL_SHIFT   0
#define APU_XPD_CTRL1_CLK_SEL_WIDTH   2
#define APU_XPD_CTRL1_CLK_SEL_MASK    0x00000003
#define APU_XPD_CTRL1_CLK_SEL_DEFVAL  0x0

/**
 * Register: APU_XPD_CTRL2
 */
#define APU_XPD_CTRL2    ( ( APU_BASEADDR ) + 0x00000614 )
#define APU_XPD_CTRL2_DEFVAL   0x0

#define APU_XPD_CTRL2_CTRL_SPARE_SHIFT   1
#define APU_XPD_CTRL2_CTRL_SPARE_WIDTH   2
#define APU_XPD_CTRL2_CTRL_SPARE_MASK    0x00000006
#define APU_XPD_CTRL2_CTRL_SPARE_DEFVAL  0x0

#define APU_XPD_CTRL2_ENABLE_SHIFT   0
#define APU_XPD_CTRL2_ENABLE_WIDTH   1
#define APU_XPD_CTRL2_ENABLE_MASK    0x00000001
#define APU_XPD_CTRL2_ENABLE_DEFVAL  0x0

/**
 * Register: APU_XPD_CTRL3
 */
#define APU_XPD_CTRL3    ( ( APU_BASEADDR ) + 0x00000618 )
#define APU_XPD_CTRL3_DEFVAL   0x0

#define APU_XPD_CTRL3_DCYCLE_CNT_VALUE_SHIFT   3
#define APU_XPD_CTRL3_DCYCLE_CNT_VALUE_WIDTH   12
#define APU_XPD_CTRL3_DCYCLE_CNT_VALUE_MASK    0x00007ff8
#define APU_XPD_CTRL3_DCYCLE_CNT_VALUE_DEFVAL  0x0

#define APU_XPD_CTRL3_DCYCLE_HIGH_LOW_SHIFT   2
#define APU_XPD_CTRL3_DCYCLE_HIGH_LOW_WIDTH   1
#define APU_XPD_CTRL3_DCYCLE_HIGH_LOW_MASK    0x00000004
#define APU_XPD_CTRL3_DCYCLE_HIGH_LOW_DEFVAL  0x0

#define APU_XPD_CTRL3_DCYCLE_CNT_CLR_SHIFT   1
#define APU_XPD_CTRL3_DCYCLE_CNT_CLR_WIDTH   1
#define APU_XPD_CTRL3_DCYCLE_CNT_CLR_MASK    0x00000002
#define APU_XPD_CTRL3_DCYCLE_CNT_CLR_DEFVAL  0x0

#define APU_XPD_CTRL3_DCYCLE_START_SHIFT   0
#define APU_XPD_CTRL3_DCYCLE_START_WIDTH   1
#define APU_XPD_CTRL3_DCYCLE_START_MASK    0x00000001
#define APU_XPD_CTRL3_DCYCLE_START_DEFVAL  0x0

/**
 * Register: APU_XPD_SOFT_RST
 */
#define APU_XPD_SOFT_RST    ( ( APU_BASEADDR ) + 0x0000061C )
#define APU_XPD_SOFT_RST_DEFVAL   0x0

#define APU_XPD_SOFT_RST_CLK2_SHIFT   2
#define APU_XPD_SOFT_RST_CLK2_WIDTH   1
#define APU_XPD_SOFT_RST_CLK2_MASK    0x00000004
#define APU_XPD_SOFT_RST_CLK2_DEFVAL  0x0

#define APU_XPD_SOFT_RST_CLK1_SHIFT   1
#define APU_XPD_SOFT_RST_CLK1_WIDTH   1
#define APU_XPD_SOFT_RST_CLK1_MASK    0x00000002
#define APU_XPD_SOFT_RST_CLK1_DEFVAL  0x0

#define APU_XPD_SOFT_RST_CLK0_SHIFT   0
#define APU_XPD_SOFT_RST_CLK0_WIDTH   1
#define APU_XPD_SOFT_RST_CLK0_MASK    0x00000001
#define APU_XPD_SOFT_RST_CLK0_DEFVAL  0x0

/**
 * Register: APU_XPD_STAT
 */
#define APU_XPD_STAT    ( ( APU_BASEADDR ) + 0x00000620 )
#define APU_XPD_STAT_DEFVAL   0x0

#define APU_XPD_STAT_CMP_RESULT_SHIFT   1
#define APU_XPD_STAT_CMP_RESULT_WIDTH   1
#define APU_XPD_STAT_CMP_RESULT_MASK    0x00000002
#define APU_XPD_STAT_CMP_RESULT_DEFVAL  0x0

#define APU_XPD_STAT_CMP_DONE_SHIFT   0
#define APU_XPD_STAT_CMP_DONE_WIDTH   1
#define APU_XPD_STAT_CMP_DONE_MASK    0x00000001
#define APU_XPD_STAT_CMP_DONE_DEFVAL  0x0

#ifdef __cplusplus
}
#endif

#endif /* __APU_H__ */
