#ifndef _IPIBUF_H_
#define _IPIBUF_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * IPU Buffer Base Address
 */
#define IPIBUF_BASEADDR      0xFF990000


/**
 * Processing Unit Source IPI Buffer Offsets
 */
#define IPIBUF_RPU0_OFFSET      0x000
#define IPIBUF_RPU1_OFFSET      0x200
#define IPIBUF_APU_OFFSET       0x400
#define IPIBUF_PL0_OFFSET       0x600
#define IPIBUF_PL1_OFFSET       0x800
#define IPIBUF_PL2_OFFSET       0xA00
#define IPIBUF_PL3_OFFSET       0xC00
#define IPIBUF_PMU_OFFSET       0xE00

/**
 * Processing Unit Destination IPI Buffer Offsets
 */
#define IPIBUF_RPU0_REQ_OFFSET     0x000
#define IPIBUF_RPU0_RESP_OFFSET    0x020
#define IPIBUF_RPU1_REQ_OFFSET     0x040
#define IPIBUF_RPU1_RESP_OFFSET    0x060
#define IPIBUF_APU_REQ_OFFSET      0x080
#define IPIBUF_APU_RESP_OFFSET     0x0A0
#define IPIBUF_PL0_REQ_OFFSET      0x0C0
#define IPIBUF_PL0_RESP_OFFSET     0x0E0
#define IPIBUF_PL1_REQ_OFFSET      0x100
#define IPIBUF_PL1_RESP_OFFSET     0x120
#define IPIBUF_PL2_REQ_OFFSET      0x140
#define IPIBUF_PL2_RESP_OFFSET     0x160
#define IPIBUF_PL3_REQ_OFFSET      0x180
#define IPIBUF_PL3_RESP_OFFSET     0x1A0
#define IPIBUF_PMU_REQ_OFFSET      0x1C0
#define IPIBUF_PMU_RESP_OFFSET     0x1E0

/**
 * RPU0 Source IPI Buffers
 */
#define IPIBUF_RPU0_BASEADDR        ( IPIBUF_BASEADDR + IPIBUF_RPU0_OFFSET )

#define IPIBUF_RPU0_RPU0_REQ        ( IPIBUF_RPU0_BASEADDR + IPIBUF_RPU0_REQ_OFFSET )
#define IPIBUF_RPU0_RPU0_RESP       ( IPIBUF_RPU0_BASEADDR + IPIBUF_RPU0_RESP_OFFSET )
#define IPIBUF_RPU0_RPU1_REQ        ( IPIBUF_RPU0_BASEADDR + IPIBUF_RPU1_REQ_OFFSET )
#define IPIBUF_RPU0_RPU1_RESP       ( IPIBUF_RPU0_BASEADDR + IPIBUF_RPU1_RESP_OFFSET )
#define IPIBUF_RPU0_APU_REQ         ( IPIBUF_RPU0_BASEADDR + IPIBUF_APU_REQ_OFFSET )
#define IPIBUF_RPU0_APU_RESP        ( IPIBUF_RPU0_BASEADDR + IPIBUF_APU_RESP_OFFSET )
#define IPIBUF_RPU0_PL0_REQ         ( IPIBUF_RPU0_BASEADDR + IPIBUF_PL0_REQ_OFFSET )
#define IPIBUF_RPU0_PL0_RESP        ( IPIBUF_RPU0_BASEADDR + IPIBUF_PL0_RESP_OFFSET )
#define IPIBUF_RPU0_PL1_REQ         ( IPIBUF_RPU0_BASEADDR + IPIBUF_PL1_REQ_OFFSET )
#define IPIBUF_RPU0_PL1_RESP        ( IPIBUF_RPU0_BASEADDR + IPIBUF_PL1_RESP_OFFSET )
#define IPIBUF_RPU0_PL2_REQ         ( IPIBUF_RPU0_BASEADDR + IPIBUF_PL2_REQ_OFFSET )
#define IPIBUF_RPU0_PL2_RESP        ( IPIBUF_RPU0_BASEADDR + IPIBUF_PL2_RESP_OFFSET )
#define IPIBUF_RPU0_PL3_REQ         ( IPIBUF_RPU0_BASEADDR + IPIBUF_PL3_REQ_OFFSET )
#define IPIBUF_RPU0_PL3_RESP        ( IPIBUF_RPU0_BASEADDR + IPIBUF_PL3_RESP_OFFSET )
#define IPIBUF_RPU0_PMU_REQ         ( IPIBUF_RPU0_BASEADDR + IPIBUF_PMU_REQ_OFFSET )
#define IPIBUF_RPU0_PMU_RESP        ( IPIBUF_RPU0_BASEADDR + IPIBUF_PMU_RESP_OFFSET )

/**
 * RPU1 Source IPI Buffers
 */
#define IPIBUF_RPU1_BASEADDR        ( IPIBUF_BASEADDR + IPIBUF_RPU1_OFFSET )

#define IPIBUF_RPU1_RPU0_REQ        ( IPIBUF_RPU1_BASEADDR + IPIBUF_RPU0_REQ_OFFSET )
#define IPIBUF_RPU1_RPU0_RESP       ( IPIBUF_RPU1_BASEADDR + IPIBUF_RPU0_RESP_OFFSET )
#define IPIBUF_RPU1_RPU1_REQ        ( IPIBUF_RPU1_BASEADDR + IPIBUF_RPU1_REQ_OFFSET )
#define IPIBUF_RPU1_RPU1_RESP       ( IPIBUF_RPU1_BASEADDR + IPIBUF_RPU1_RESP_OFFSET )
#define IPIBUF_RPU1_APU_REQ         ( IPIBUF_RPU1_BASEADDR + IPIBUF_APU_REQ_OFFSET )
#define IPIBUF_RPU1_APU_RESP        ( IPIBUF_RPU1_BASEADDR + IPIBUF_APU_RESP_OFFSET )
#define IPIBUF_RPU1_PL0_REQ         ( IPIBUF_RPU1_BASEADDR + IPIBUF_PL0_REQ_OFFSET )
#define IPIBUF_RPU1_PL0_RESP        ( IPIBUF_RPU1_BASEADDR + IPIBUF_PL0_RESP_OFFSET )
#define IPIBUF_RPU1_PL1_REQ         ( IPIBUF_RPU1_BASEADDR + IPIBUF_PL1_REQ_OFFSET )
#define IPIBUF_RPU1_PL1_RESP        ( IPIBUF_RPU1_BASEADDR + IPIBUF_PL1_RESP_OFFSET )
#define IPIBUF_RPU1_PL2_REQ         ( IPIBUF_RPU1_BASEADDR + IPIBUF_PL2_REQ_OFFSET )
#define IPIBUF_RPU1_PL2_RESP        ( IPIBUF_RPU1_BASEADDR + IPIBUF_PL2_RESP_OFFSET )
#define IPIBUF_RPU1_PL3_REQ         ( IPIBUF_RPU1_BASEADDR + IPIBUF_PL3_REQ_OFFSET )
#define IPIBUF_RPU1_PL3_RESP        ( IPIBUF_RPU1_BASEADDR + IPIBUF_PL3_RESP_OFFSET )
#define IPIBUF_RPU1_PMU_REQ         ( IPIBUF_RPU1_BASEADDR + IPIBUF_PMU_REQ_OFFSET )
#define IPIBUF_RPU1_PMU_RESP        ( IPIBUF_RPU1_BASEADDR + IPIBUF_PMU_RESP_OFFSET )

/**
 * APU Source IPI Buffers
 */
#define IPIBUF_APU_BASEADDR        ( IPIBUF_BASEADDR + IPIBUF_APU_OFFSET )

#define IPIBUF_APU_RPU0_REQ        ( IPIBUF_APU_BASEADDR + IPIBUF_RPU0_REQ_OFFSET )
#define IPIBUF_APU_RPU0_RESP       ( IPIBUF_APU_BASEADDR + IPIBUF_RPU0_RESP_OFFSET )
#define IPIBUF_APU_RPU1_REQ        ( IPIBUF_APU_BASEADDR + IPIBUF_RPU1_REQ_OFFSET )
#define IPIBUF_APU_RPU1_RESP       ( IPIBUF_APU_BASEADDR + IPIBUF_RPU1_RESP_OFFSET )
#define IPIBUF_APU_APU_REQ         ( IPIBUF_APU_BASEADDR + IPIBUF_APU_REQ_OFFSET )
#define IPIBUF_APU_APU_RESP        ( IPIBUF_APU_BASEADDR + IPIBUF_APU_RESP_OFFSET )
#define IPIBUF_APU_PL0_REQ         ( IPIBUF_APU_BASEADDR + IPIBUF_PL0_REQ_OFFSET )
#define IPIBUF_APU_PL0_RESP        ( IPIBUF_APU_BASEADDR + IPIBUF_PL0_RESP_OFFSET )
#define IPIBUF_APU_PL1_REQ         ( IPIBUF_APU_BASEADDR + IPIBUF_PL1_REQ_OFFSET )
#define IPIBUF_APU_PL1_RESP        ( IPIBUF_APU_BASEADDR + IPIBUF_PL1_RESP_OFFSET )
#define IPIBUF_APU_PL2_REQ         ( IPIBUF_APU_BASEADDR + IPIBUF_PL2_REQ_OFFSET )
#define IPIBUF_APU_PL2_RESP        ( IPIBUF_APU_BASEADDR + IPIBUF_PL2_RESP_OFFSET )
#define IPIBUF_APU_PL3_REQ         ( IPIBUF_APU_BASEADDR + IPIBUF_PL3_REQ_OFFSET )
#define IPIBUF_APU_PL3_RESP        ( IPIBUF_APU_BASEADDR + IPIBUF_PL3_RESP_OFFSET )
#define IPIBUF_APU_PMU_REQ         ( IPIBUF_APU_BASEADDR + IPIBUF_PMU_REQ_OFFSET )
#define IPIBUF_APU_PMU_RESP        ( IPIBUF_APU_BASEADDR + IPIBUF_PMU_RESP_OFFSET )

/**
 * PL0 Source IPI Buffers
 */
#define IPIBUF_PL0_BASEADDR        ( IPIBUF_BASEADDR + IPIBUF_PL0_OFFSET )

#define IPIBUF_PL0_RPU0_REQ        ( IPIBUF_PL0_BASEADDR + IPIBUF_RPU0_REQ_OFFSET )
#define IPIBUF_PL0_RPU0_RESP       ( IPIBUF_PL0_BASEADDR + IPIBUF_RPU0_RESP_OFFSET )
#define IPIBUF_PL0_RPU1_REQ        ( IPIBUF_PL0_BASEADDR + IPIBUF_RPU1_REQ_OFFSET )
#define IPIBUF_PL0_RPU1_RESP       ( IPIBUF_PL0_BASEADDR + IPIBUF_RPU1_RESP_OFFSET )
#define IPIBUF_PL0_APU_REQ         ( IPIBUF_PL0_BASEADDR + IPIBUF_APU_REQ_OFFSET )
#define IPIBUF_PL0_APU_RESP        ( IPIBUF_PL0_BASEADDR + IPIBUF_APU_RESP_OFFSET )
#define IPIBUF_PL0_PL0_REQ         ( IPIBUF_PL0_BASEADDR + IPIBUF_PL0_REQ_OFFSET )
#define IPIBUF_PL0_PL0_RESP        ( IPIBUF_PL0_BASEADDR + IPIBUF_PL0_RESP_OFFSET )
#define IPIBUF_PL0_PL1_REQ         ( IPIBUF_PL0_BASEADDR + IPIBUF_PL1_REQ_OFFSET )
#define IPIBUF_PL0_PL1_RESP        ( IPIBUF_PL0_BASEADDR + IPIBUF_PL1_RESP_OFFSET )
#define IPIBUF_PL0_PL2_REQ         ( IPIBUF_PL0_BASEADDR + IPIBUF_PL2_REQ_OFFSET )
#define IPIBUF_PL0_PL2_RESP        ( IPIBUF_PL0_BASEADDR + IPIBUF_PL2_RESP_OFFSET )
#define IPIBUF_PL0_PL3_REQ         ( IPIBUF_PL0_BASEADDR + IPIBUF_PL3_REQ_OFFSET )
#define IPIBUF_PL0_PL3_RESP        ( IPIBUF_PL0_BASEADDR + IPIBUF_PL3_RESP_OFFSET )
#define IPIBUF_PL0_PMU_REQ         ( IPIBUF_PL0_BASEADDR + IPIBUF_PMU_REQ_OFFSET )
#define IPIBUF_PL0_PMU_RESP        ( IPIBUF_PL0_BASEADDR + IPIBUF_PMU_RESP_OFFSET )

/**
 * PL1 Source IPI Buffers
 */
#define IPIBUF_PL1_BASEADDR        ( IPIBUF_BASEADDR + IPIBUF_PL1_OFFSET )

#define IPIBUF_PL1_RPU0_REQ        ( IPIBUF_PL1_BASEADDR + IPIBUF_RPU0_REQ_OFFSET )
#define IPIBUF_PL1_RPU0_RESP       ( IPIBUF_PL1_BASEADDR + IPIBUF_RPU0_RESP_OFFSET )
#define IPIBUF_PL1_RPU1_REQ        ( IPIBUF_PL1_BASEADDR + IPIBUF_RPU1_REQ_OFFSET )
#define IPIBUF_PL1_RPU1_RESP       ( IPIBUF_PL1_BASEADDR + IPIBUF_RPU1_RESP_OFFSET )
#define IPIBUF_PL1_APU_REQ         ( IPIBUF_PL1_BASEADDR + IPIBUF_APU_REQ_OFFSET )
#define IPIBUF_PL1_APU_RESP        ( IPIBUF_PL1_BASEADDR + IPIBUF_APU_RESP_OFFSET )
#define IPIBUF_PL1_PL0_REQ         ( IPIBUF_PL1_BASEADDR + IPIBUF_PL0_REQ_OFFSET )
#define IPIBUF_PL1_PL0_RESP        ( IPIBUF_PL1_BASEADDR + IPIBUF_PL0_RESP_OFFSET )
#define IPIBUF_PL1_PL1_REQ         ( IPIBUF_PL1_BASEADDR + IPIBUF_PL1_REQ_OFFSET )
#define IPIBUF_PL1_PL1_RESP        ( IPIBUF_PL1_BASEADDR + IPIBUF_PL1_RESP_OFFSET )
#define IPIBUF_PL1_PL2_REQ         ( IPIBUF_PL1_BASEADDR + IPIBUF_PL2_REQ_OFFSET )
#define IPIBUF_PL1_PL2_RESP        ( IPIBUF_PL1_BASEADDR + IPIBUF_PL2_RESP_OFFSET )
#define IPIBUF_PL1_PL3_REQ         ( IPIBUF_PL1_BASEADDR + IPIBUF_PL3_REQ_OFFSET )
#define IPIBUF_PL1_PL3_RESP        ( IPIBUF_PL1_BASEADDR + IPIBUF_PL3_RESP_OFFSET )
#define IPIBUF_PL1_PMU_REQ         ( IPIBUF_PL1_BASEADDR + IPIBUF_PMU_REQ_OFFSET )
#define IPIBUF_PL1_PMU_RESP        ( IPIBUF_PL1_BASEADDR + IPIBUF_PMU_RESP_OFFSET )

/**
 * PL2 Source IPI Buffers
 */
#define IPIBUF_PL2_BASEADDR        ( IPIBUF_BASEADDR + IPIBUF_PL2_OFFSET )

#define IPIBUF_PL2_RPU0_REQ        ( IPIBUF_PL2_BASEADDR + IPIBUF_RPU0_REQ_OFFSET )
#define IPIBUF_PL2_RPU0_RESP       ( IPIBUF_PL2_BASEADDR + IPIBUF_RPU0_RESP_OFFSET )
#define IPIBUF_PL2_RPU1_REQ        ( IPIBUF_PL2_BASEADDR + IPIBUF_RPU1_REQ_OFFSET )
#define IPIBUF_PL2_RPU1_RESP       ( IPIBUF_PL2_BASEADDR + IPIBUF_RPU1_RESP_OFFSET )
#define IPIBUF_PL2_APU_REQ         ( IPIBUF_PL2_BASEADDR + IPIBUF_APU_REQ_OFFSET )
#define IPIBUF_PL2_APU_RESP        ( IPIBUF_PL2_BASEADDR + IPIBUF_APU_RESP_OFFSET )
#define IPIBUF_PL2_PL0_REQ         ( IPIBUF_PL2_BASEADDR + IPIBUF_PL0_REQ_OFFSET )
#define IPIBUF_PL2_PL0_RESP        ( IPIBUF_PL2_BASEADDR + IPIBUF_PL0_RESP_OFFSET )
#define IPIBUF_PL2_PL1_REQ         ( IPIBUF_PL2_BASEADDR + IPIBUF_PL1_REQ_OFFSET )
#define IPIBUF_PL2_PL1_RESP        ( IPIBUF_PL2_BASEADDR + IPIBUF_PL1_RESP_OFFSET )
#define IPIBUF_PL2_PL2_REQ         ( IPIBUF_PL2_BASEADDR + IPIBUF_PL2_REQ_OFFSET )
#define IPIBUF_PL2_PL2_RESP        ( IPIBUF_PL2_BASEADDR + IPIBUF_PL2_RESP_OFFSET )
#define IPIBUF_PL2_PL3_REQ         ( IPIBUF_PL2_BASEADDR + IPIBUF_PL3_REQ_OFFSET )
#define IPIBUF_PL2_PL3_RESP        ( IPIBUF_PL2_BASEADDR + IPIBUF_PL3_RESP_OFFSET )
#define IPIBUF_PL2_PMU_REQ         ( IPIBUF_PL2_BASEADDR + IPIBUF_PMU_REQ_OFFSET )
#define IPIBUF_PL2_PMU_RESP        ( IPIBUF_PL2_BASEADDR + IPIBUF_PMU_RESP_OFFSET )

/**
 * PL3 Source IPI Buffers
 */
#define IPIBUF_PL3_BASEADDR        ( IPIBUF_BASEADDR + IPIBUF_PL3_OFFSET )

#define IPIBUF_PL3_RPU0_REQ        ( IPIBUF_PL3_BASEADDR + IPIBUF_RPU0_REQ_OFFSET )
#define IPIBUF_PL3_RPU0_RESP       ( IPIBUF_PL3_BASEADDR + IPIBUF_RPU0_RESP_OFFSET )
#define IPIBUF_PL3_RPU1_REQ        ( IPIBUF_PL3_BASEADDR + IPIBUF_RPU1_REQ_OFFSET )
#define IPIBUF_PL3_RPU1_RESP       ( IPIBUF_PL3_BASEADDR + IPIBUF_RPU1_RESP_OFFSET )
#define IPIBUF_PL3_APU_REQ         ( IPIBUF_PL3_BASEADDR + IPIBUF_APU_REQ_OFFSET )
#define IPIBUF_PL3_APU_RESP        ( IPIBUF_PL3_BASEADDR + IPIBUF_APU_RESP_OFFSET )
#define IPIBUF_PL3_PL0_REQ         ( IPIBUF_PL3_BASEADDR + IPIBUF_PL0_REQ_OFFSET )
#define IPIBUF_PL3_PL0_RESP        ( IPIBUF_PL3_BASEADDR + IPIBUF_PL0_RESP_OFFSET )
#define IPIBUF_PL3_PL1_REQ         ( IPIBUF_PL3_BASEADDR + IPIBUF_PL1_REQ_OFFSET )
#define IPIBUF_PL3_PL1_RESP        ( IPIBUF_PL3_BASEADDR + IPIBUF_PL1_RESP_OFFSET )
#define IPIBUF_PL3_PL2_REQ         ( IPIBUF_PL3_BASEADDR + IPIBUF_PL2_REQ_OFFSET )
#define IPIBUF_PL3_PL2_RESP        ( IPIBUF_PL3_BASEADDR + IPIBUF_PL2_RESP_OFFSET )
#define IPIBUF_PL3_PL3_REQ         ( IPIBUF_PL3_BASEADDR + IPIBUF_PL3_REQ_OFFSET )
#define IPIBUF_PL3_PL3_RESP        ( IPIBUF_PL3_BASEADDR + IPIBUF_PL3_RESP_OFFSET )
#define IPIBUF_PL3_PMU_REQ         ( IPIBUF_PL3_BASEADDR + IPIBUF_PMU_REQ_OFFSET )
#define IPIBUF_PL3_PMU_RESP        ( IPIBUF_PL3_BASEADDR + IPIBUF_PMU_RESP_OFFSET )

/**
 * PMU Source IPI Buffers
 */
#define IPIBUF_PMU_BASEADDR        ( IPIBUF_BASEADDR + IPIBUF_PMU_OFFSET )

#define IPIBUF_PMU_RPU0_REQ        ( IPIBUF_PMU_BASEADDR + IPIBUF_RPU0_REQ_OFFSET )
#define IPIBUF_PMU_RPU0_RESP       ( IPIBUF_PMU_BASEADDR + IPIBUF_RPU0_RESP_OFFSET )
#define IPIBUF_PMU_RPU1_REQ        ( IPIBUF_PMU_BASEADDR + IPIBUF_RPU1_REQ_OFFSET )
#define IPIBUF_PMU_RPU1_RESP       ( IPIBUF_PMU_BASEADDR + IPIBUF_RPU1_RESP_OFFSET )
#define IPIBUF_PMU_APU_REQ         ( IPIBUF_PMU_BASEADDR + IPIBUF_APU_REQ_OFFSET )
#define IPIBUF_PMU_APU_RESP        ( IPIBUF_PMU_BASEADDR + IPIBUF_APU_RESP_OFFSET )
#define IPIBUF_PMU_PL0_REQ         ( IPIBUF_PMU_BASEADDR + IPIBUF_PL0_REQ_OFFSET )
#define IPIBUF_PMU_PL0_RESP        ( IPIBUF_PMU_BASEADDR + IPIBUF_PL0_RESP_OFFSET )
#define IPIBUF_PMU_PL1_REQ         ( IPIBUF_PMU_BASEADDR + IPIBUF_PL1_REQ_OFFSET )
#define IPIBUF_PMU_PL1_RESP        ( IPIBUF_PMU_BASEADDR + IPIBUF_PL1_RESP_OFFSET )
#define IPIBUF_PMU_PL2_REQ         ( IPIBUF_PMU_BASEADDR + IPIBUF_PL2_REQ_OFFSET )
#define IPIBUF_PMU_PL2_RESP        ( IPIBUF_PMU_BASEADDR + IPIBUF_PL2_RESP_OFFSET )
#define IPIBUF_PMU_PL3_REQ         ( IPIBUF_PMU_BASEADDR + IPIBUF_PL3_REQ_OFFSET )
#define IPIBUF_PMU_PL3_RESP        ( IPIBUF_PMU_BASEADDR + IPIBUF_PL3_RESP_OFFSET )
#define IPIBUF_PMU_PMU_REQ         ( IPIBUF_PMU_BASEADDR + IPIBUF_PMU_REQ_OFFSET )
#define IPIBUF_PMU_PMU_RESP        ( IPIBUF_PMU_BASEADDR + IPIBUF_PMU_RESP_OFFSET )

#ifdef __cplusplus
}
#endif


#endif /* _IPIBUF_H_ */
